name: Frontend CI

on: ["pull_request"]

jobs:
  CI:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - name: Checkout code repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install pnpm
        run: npm i pnpm@latest -g

      - name: Install modules
        run: pnpm i

      - name: Lint
        run: pnpm lint

      - name: Prettier
        run: pnpm prettier

      - name: Build
        run: pnpm build
